### ISSUE TITLE
Integrate with Active Directory for authorization 

### ISSUE THREAD

**Issue by wochanda** [aws-samples/simple-file-manager-for-amazon-efs#152]
**Is your feature request related to a problem? Please describe.**
My users authenticate using Active Directory (AD), and I would like to use AD to authorize access to perform file operations on my Amazon EFS file system.

**Describe the feature you'd like**
Rather than configure a static user/password when I deploy simple file manager, I want to provide my AD endpoint. For each file system, I should be able to provide AD users or groups who are permitted to read/write/list data in the file system.

**Additional context**

**Comment by brandold** [comment]
Closing in lieu of #158
