### ISSUE TITLE
Cloudformation failing to create S3 bucket

### ISSUE THREAD

**Issue by akfroman** [aws-samples/simple-file-manager-for-amazon-efs#153]
**Describe the bug**
When attempting to deploy Simple File Manager using the cloud formation template in the below link, The deployment fails when trying to deploy the nested stack `EFSFileWebApplication`. It starts to create the `EFSFileSimpleWebsiteBucket` resource, but fails with the message "Bucket name should be between 3 and 63 characters long". I'm guessing this means there's something wrong with the `WebsiteBucketNameFunction` lambda resource.

**To Reproduce**
Launch cloudformation with this template:
https://s3.amazonaws.com/solutions-reference/simple-file-manager-for-amazon-efs/latest/simple-file-manager-for-amazon-efs.template

**Expected behavior**
Cloudformation stack should deploy successfully.

**Please complete the following information about the solution:**
- [ ] Version: 1.4.0
- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? When looking at the WebsiteBucketNameFunction logs, the Status was "Success", however the body was empty.

**Screenshots**

**Additional context**
I am launching this template with full Admin permissions.

**Comment by brandold** [comment]
Hey @akfroman,

Working back from your description, it sounds like you're reaching a naming limit for the bucket resource. My initial guess is the stack name you provided (which is prepended to the bucket resource name) is causing that limit to be reached. 

Could you share how many characters the stack name you attempted to deploy had? Another thing you could do is attempt to deploy the solution with a shorter stack name (sounds like we'll need to document this limit, fyi).

**Comment by akfroman** [comment]
That was the issue. The old stack name was 25 characters.

**Comment by brandold** [comment]
Gotcha, thanks for the report. I'll cut another tracking issue to get the limits better defined. Closing this issue out.
