### ISSUE TITLE
 The following resource(s) failed to create: [EFSFileSimpleWebsiteBucket]

### ISSUE THREAD

**Issue by rcastagnet** [aws-samples/simple-file-manager-for-amazon-efs#157]
**Describe the bug**
The following resource(s) failed to create: [EFSFileWebApplication].
The following resource(s) failed to create: [EFSFileSimpleWebsiteBucket]. 

No more information in the logs....

**To Reproduce**
Following : https://docs.aws.amazon.com/solutions/latest/simple-file-manager-for-amazon-efs/automated-deployment.html

**Expected behavior**
I would like to have a complete creation.

**Please complete the following information about the solution:**
- [ ] Version: 
  -> v1.4.0
- [ ] Region: 
  -> eu-west-1
- [ ] Was the solution modified from the version published on this repository? 
  -> No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? 
  -> Yes, but which one ?
- [ ] Were there any errors in the CloudWatch Logs? 
  -> No logs

**Comment by brandold** [comment]
Hi @rcastagnet,

Can you check the events tab for information on why the solution failed to deploy? The messages there are usually very descriptive. 

If the stack is deleted before you're able to check the output, you can turn off "rollback on failure" in the stack creation dialog.

![stack_rollback](https://user-images.githubusercontent.com/46355297/129774341-d1aec695-5ef2-426f-bae8-bd4d36554e06.png)

Some general things to check as well:

1. Try a shorter stack name - you may be running up against a limit there (we have an open item to document the exact limit)
2. Ensure you haven't reached the max number of S3 buckets in your account

**Comment by brandold** [comment]
Hi @rcastagnet,

It looks like this issue is getting stale. I'm going to close it for now, but feel free to reopen it if you continue to have issues.
