### ISSUE TITLE
SM - API Gateway configuration Add Xray logging for all API paths. 

### ISSUE THREAD

**Issue by eggoynes** [aws-samples/simple-file-manager-for-amazon-efs#87]
After researching I found that if I enable in Chalice it will also add it to API Gateway. 

Reading through the PR to add support it looks like I can just add this to the config.json for Chalice.
aws/chalice@922fb57

Here it is in the documentation.
https://aws.github.io/chalice/topics/configfile.html?highlight=xray

It adds Xray for Lambda paths, as well as all API Gateway paths.

**Comment by brandold** [comment]
This should be a configurable option, e.g. not enabled by default.

**Comment by dreamorosi** [comment]
It seems Chalice doesn't support this for API Gw stages but only for functions, see #86 for more details.

**Comment by brandold** [comment]
Closing in lieu of #86
